# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# Answer:
# 4613732

max = 4_000_000
sum = 0
a = 1
b = 1   
while b < max
  sum += b if b % 2 == 0
  h = a + b
  a = b  
  b = h
end
puts sum
 
# real    0m0.150s
# user    0m0.068s 
# sys     0m0.076s
  
########################### Refactored ###########################
 
max = 4_000_000
sum = 0
a = 1
b = 1
c = a + b
while c < max
  sum += c
  a = b + c
  b = c + a
  c = a + b
end
puts sum

# real    0m0.154s
# user    0m0.052s
# sys     0m0.100s